name: flutter_ui_factory  # Must be unique on pub.dev
description: A Flutter UI factory for generating complete screens and components without Figma.
version: 1.0.0  # Follow semantic versioning (e.g., 1.0.0+1)
homepage: https://github.com/yourusername/flutter_ui_factory  # Optional but recommended
repository: https://github.com/yourusername/flutter_ui_factory.git  # Optional
issue_tracker: https://github.com/yourusername/flutter_ui_factory/issues  # Optional

environment:
  sdk: '>=3.0.0 <4.0.0'  # Ensure Dart 3+ compatibility
  flutter: '>=3.0.0'  # Specify Flutter version

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # For code analysis

flutter:
  uses-material-design: true